### ISSUE TITLE
libsodium required as dependency

### ISSUE THREAD

**Issue by andrew101sanders** [ilikdoge/sange#2]
I was given this error when running "npm i git://github.com/ilikdoge/sange.git":

"npm ERR! ../src/wrapper.cpp:4:10: fatal error: sodium/crypto_secretbox.h: No such file or directory"

It was resolved once libsodium (mention as a yasha dependency) was installed.

**Comment by davidzeng0** [comment]
This is known. I don't really expect people to install sange without yasha as well so I didn't really bother to fix it. If you are only installing sange without yasha then I can consider updating the dependency list.

**Comment by andrew101sanders** [comment]
Gotcha, thanks!
